spring:
    resources:
      staticLocations:
        - file:${thecodestein.staticResourcesPath}
        - file:${thecodestein.articlesPath}

thecodestein:
  staticResourcesPath: /home/pi/thecodestein-backend/public/
  articlesRelativePath: articles/
  articlesFullPath: ${thecodestein.staticResourcesPath}${thecodestein.articlesRelativePath}
  contextUrl: http://thecodestein.com/

---
spring:
    profiles: dev

thecodestein:
  staticResourcesPath: /Users/ricardo/git/thecodestein.com/dist/
  articlesRelativePath: static/
  contextUrl: http://localhost:8080/
