spring:
    resources:
      staticLocations:
        - file:${thecodestein.staticResourcesPath}

thecodestein:
  staticResourcesPath: /usr/share/www/
  articlesRelativePath: articles/
  articlesFullPath: ${thecodestein.staticResourcesPath}${thecodestein.articlesRelativePath}

---
spring:
    profiles: dev

thecodestein:
  staticResourcesPath: /Users/ricardo/git/thecodestein.com/dist/
  articlesRelativePath: static/
